In [8]:
import numpy as np
arr=np.array([1,2,3,4])
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)

[1 2 3 4]
<class 'numpy.ndarray'>
int32
(4,)


In [3]:
import numpy as np
import time
size=10_000_000
py_lis=list(range(size))
start=time.time()
sqr=[i**2 for i in py_lis]
end=time.time()
print(f"time={end-start}")

np_arr=np.array(py_lis)
start=time.time()
np_sqr=np_arr**2
end=time.time()
print(f"time={end-start}")




time=2.3884201049804688
time=0.031914472579956055


In [5]:
import sys
print(f"python list size={sys.getsizeof(py_lis) * len(py_lis)} bytes")

print(np_arr.nbytes)

python list size=800000560000000 bytes
40000000


In [30]:
import numpy as np
arr1=np.zeros((3,3) ,dtype="int64")
arr2=np.ones(2)
arr3=np.full((1,10),12)
arr4=np.eye(2,dtype="int64")
arr5=np.arange(1,17,2)
arr6=np.linspace(1,100,4)
print(arr1)
print(arr2)
print(arr3)
print(arr4)
print(arr5)
print(arr6)

[  1.  34.  67. 100.]


In [33]:
#properties
import numpy as numpy
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)
print(arr.shape)
print(arr.dtype)
print(arr.ndim)
float_arr=arr.astype(np.float64)
print(float_arr,float_arr.dtype)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)
int32
2
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]] float64


In [39]:
#operation
import numpy as numpy
arr=np.array([[1,2],[4,5],[7,8]])
reshape=arr.reshape(2,3)
print(arr.shape)
print(reshape.shape)
flattend=arr.flatten()
print(flattend.shape)


(3, 2)
(2, 3)
(6,)


In [44]:
#indexing
import numpy as numpy
arr=np.array([[1,2],[4,5],[7,8]])
print(arr[0][1])
#fancing idexsing
idx=[1,2]
print(arr[idx])
#boolean indexing
print(arr[arr>5])
print(arr[arr%2==0])


2
[[4 5]
 [7 8]]
[7 8]
[2 4 8]


In [45]:
#slicing
import numpy as np
arr=np.array([1,2,3,4,5,6,7])
print(arr[0:])
print(arr[1:3])
print(arr[1:7:2])

[1 2 3 4 5 6 7]
[2 3]
[2 4 6]


In [47]:
#copy vs view 
nums=[1,2,3,4,5]
sub_list=nums[1:3]
print(sub_list)
sub_list[0]=200
print(sub_list)
print(nums)

import numpy as np
arr=np.array([1,2,3,4,5])
sub_arr=arr[1:3]
print(sub_arr)
sub_arr[0]=200
print(sub_arr)
print(arr)

[2, 3]
[200, 3]
[1, 2, 3, 4, 5]
[2 3]
[200   3]
[  1 200   3   4   5]


In [49]:
import numpy as numpy
arr=np.array([[1,2],[4,5],[7,8]])
Row_sum=arr.sum(axis=1)
Col_sum=arr.sum(axis=0)
print(Row_sum)
print(Col_sum)

[ 3  9 15]
[12 15]


In [62]:
#3D Array
import numpy as np
arr1=np.array([[[1,2],[3,4],[5,6]],[[7,8],[9,10],[11,12]]])
print(np.ndim(arr1))
print(arr1[0][1][1])
print(arr1[0,1,1])
print(arr1[:,0,:])

3
4
4
[[1 2]
 [7 8]]


In [1]:
#normalization
import numpy as np
arr=np.array([[1,2],[3,4]])
mean=np.mean(arr)
std_dev=np.std(arr)
normalized_arr=(arr-mean)/std_dev
print(mean)
print(std_dev)
print(normalized_arr)

2.5
1.118033988749895
[[-1.34164079 -0.4472136 ]
 [ 0.4472136   1.34164079]]


In [5]:
#mathmatics Fnx
#aggregation



import numpy as np
arr=np.array([1,2,3,4,5])
print(np.sum(arr))
print(np.min(arr))
print(np.log2(arr))
print(np.power(arr,2))
print(np.argmin(arr))
print(np.round(4.9))
print(np.floor(3.9))
print(np.ceil(3.8))
print(np.trunc(2.9080))



15
1
[0.         1.         1.5849625  2.         2.32192809]
[ 1  4  9 16 25]
0
5.0
3.0
4.0
2.0
